mesosphere/mindthegap

make/platform.mk, make/shell.mk
1. I have `bash` that I installed with `brew`
```
➜  mindthegap git:(dkoshkin/darwin-fixes) bash --version
GNU bash, version 5.1.12(1)-release (x86_64-apple-darwin20.6.0)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
But `SHELL := /bin/bash` uses the default old version that comes with Darwin.
---
2. I think you meant to discard just stderr instead of `brew --prefix &>/dev/null`?
=> fix: Makefile utils for Darwin

skopeo/default-policy.json, skopeo/skopeo.go
Works around the error `Error loading trust policy: open
/etc/containers/policy.json: no such file or directory`.
=> fix: Embed default policy in binary

README.md, cmd/push/imagebundle/image_bundle.go, cmd/root.go, cmd/serve/imagebundle/image_bundle.go, cmd/serve/serve.go, docker/registry/registry.go
This commit adds a new subcommand that starts a docker registry serving the
images from the specified bundle.
=> feat: Add serve image-bundle subcommand

skopeo/default-policy.json
Fixes issue
```
➜  dist/mindthegap_darwin_amd64/mindthegap create image-bundle --images-file images-example.yaml
✓ Checking if output file already exists
✓ Parsing image bundle config
✓ Starting temporary Docker registry
⢄⡱ Copying k8s.gcr.io/kube-state-metrics/kube-state-metrics:v1.9.8 (platforms: [linux/amd64]) I0104 09:46:39.182417   19850 image_bundle.go:176] time="2022-01-04T09:46:39-08:00" level=fatal msg="Error loading trust policy: invalid policy in \"/var/folders/cf/02pp6nwj3sg15xdml78ytqfc0000gq/T/skopeo-2928207020/policy.json\": invalid character '/' looking for beginning of value"
✗ Copying k8s.gcr.io/kube-state-metrics/kube-state-metrics:v1.9.8 (platforms: [linux/amd64])
Error: exit status 1
```
=> fix: comments in  skopeo policy.json

cmd/serve/imagebundle/image_bundle.go, docker/registry/registry.go, docker/registry/registry_test.go
New flags `--tls-cert-file` and `--tls-private-key-file` to support serving the docker registry with TLS enabled.
Tested creating a registry:
```
● mindthegap-registry.service - Run a docker registry using mindthegap
Loaded: loaded (/usr/lib/systemd/system/mindthegap-registry.service; enabled; vendor preset: disabled)
Active: active (running) since Wed 2022-01-26 01:06:31 UTC; 6min ago
Main PID: 21681 (mindthegap)
Tasks: 10
Memory: 1.5G
CGroup: /system.slice/mindthegap-registry.service
└─21681 /home/centos/mindthegap serve image-bundle --image-bundle /home/centos/images.tar --listen-address 10.0.82.168 --listen-port 5000 --tls-cert-file /home/centos/registry/certs/server.crt --tls-private-key-file /home/centos/registry/certs/server.key
Jan 26 01:06:31 …
```
=> feat: Support optional TLS when serving docker registry

cmd/create/imagebundle/image_bundle.go
In reality, this makes no difference because the contents
is already compressed by virtue of being built via docker registry,
but having a GZ extension improves the UX and prevents users from
thinking they can make it smaller by gzipping it.
=> feat: Gzip image bundle tarball

skopeo/skopeo.go
The string we want to check is in stderr
```
[centos@ip-172-31-17-125 ~]$ /home/centos/mindthegap create image-bundle --images-file images.txt
✓ Checking if output file already exists
✓ Parsing image bundle config
✓ Starting temporary Docker registry
---skopeo stdout---:
---skopeo stderr---:
time="2022-01-26T16:28:19Z" level=fatal msg="not logged into gcr.io"
error logging in to registry: failed to check if already logged in to gcr.io: exit status 1
```
=> fix: Fix registry log in error checking

cleanup/cleaner.go, cmd/create/imagebundle/image_bundle.go, cmd/importcmd/imagebundle/image_bundle.go, cmd/push/imagebundle/image_bundle.go, cmd/serve/imagebundle/image_bundle.go
Previously, if any commands were interrupted, temporary directories would be left behind. This now properly cleans up when either an interrupt is received or the commands exit successfully.
=> fix: Always cleanup temporary directory

cmd/create/create.go, cmd/create/helmbundle/helm_bundle.go, cmd/create/imagebundle/image_bundle.go, cmd/importcmd/imagebundle/image_bundle.go, cmd/importcmd/import.go, cmd/push/imagebundle/image_bundle.go, cmd/push/push.go, cmd/serve/helmbundle/helm_bundle.go, cmd/serve/imagebundle/image_bundle.go, cmd/serve/serve.go
```
➜  mindthegap --help
Usage:
mindthegap [command]
Available Commands:
completion       Generate the autocompletion script for the specified shell
create           Create an tar.gz image or helm bundle
help             Help about any command
import           Import images from an image bundle into Containerd
push             Push images from an image bundle into an existing image registry
serve            Serve an image registry or a helm chart repository
version          Print version information
Flags:
-h, --help          Help for mindthegap
-v, --verbose int   Output verbosity
Use "mindthegap [command] --help" for more information about a command.
```
```
➜  mindthegap create --help
Create an tar.gz image or helm bundle
Usage:
mindthegap create [command]
Available Commands: …
```
=> feat: add command descriptions

cmd/create/helmbundle/helm_bundle.go, config/helm_charts_config.go, config/helm_charts_config_test.go, config/images_config.go, config/testdata/helmcharts/empty.yaml, config/testdata/helmcharts/multiple_repositories_with_multiple_charts_with_multiple_versions.yaml, config/testdata/helmcharts/multiple_repositories_with_tls_config.yaml, config/testdata/helmcharts/single_repository_with_chart_with_multiple_versions.yaml, config/testdata/helmcharts/single_repository_with_chart_with_no_requested_versions.yaml, config/testdata/helmcharts/single_repository_with_chart_with_single_version.yaml, config/testdata/helmcharts/single_repository_with_multiple_charts_with_multiple_versions.yaml, config/testdata/helmcharts/single_repository_with_no_charts.yaml, config/testdata/helmcharts/single_repository_with_tls_config.yaml, config/testdata/images/single_registry_with_tls_config.yaml, helm/client.go, images-example.yaml
Enables passing credentials to authenticate against a Helm repository.
Fixes #51.
=> feat: Add username and password auth to helm repository config

.goreleaser.yml
Noticed that konvoy and here had an incorrect `commitDate: "1970-01-01T00:00:00Z"`:
```
➜ ./dkp version -o yaml
diagnose:
commitDate: "2022-03-21T16:52:29Z"
compiler: gc
gitCommit: 947e77ab077fab6f1cd528421cae7173ef08efd2
gitTreeState: ""
gitVersion: v0.0.0-dev.0
goVersion: go1.17.6
major: "0"
minor: "0"
platform: darwin/amd64
dkp:
commitDate: "2022-04-04T00:51:14Z"
compiler: gc
gitCommit: 776919234cb227be7a1961fb37995a82ef1b4f28
gitTreeState: ""
gitVersion: v0.0.0-dev.0
goVersion: go1.17.8
major: "0"
minor: "0"
platform: darwin/amd64
kommander:
commitDate: "2022-04-01T18:45:56Z"
compiler: gc
gitCommit: a73ad71be53f31a48f81c1c6fdc42b15c909e52a
gitTreeState: ""
gitVersion: v2.2.0-dev
goVersion: go1.17.8
major: "2"
minor: "2"
platform: darwin/amd64
konvoy:
commitDate: "1970-01-01T00:00:00Z" …
```
=> fix: commitDate in goreleaser

go.mod, go.sum
Removing unnecessary exclude should make this build properly
go install-able.
This can be tested by running `env GOBIN=/tmp go install github.com/mesosphere/mindthegap@make-go-gettable` and checking `/tmp/mindthegap` exists after the build runs.
=> build: Make mindthegap go install-able

cmd/create/imagebundle/image_bundle.go, skopeo/skopeo.go
When using the inspect function on ECR repositories, it fails with an ominous 404.
https://github.com/containers/skopeo/issues/1230
This skips all extended tag listing -- we are happy with the one we asked for which IIUC should not be any problem for the functionality of mindthegap.
=> fix: prevent 404 on ECR during image creation

go.mod, go.sum, skopeo/skopeo.go
This follows the OCI spec better than schema2.Manifest.
=> fix: Use ocischema.Manifest for plain image details

.gitattributes, .github/workflows/checks-macos.yml, .github/workflows/codeql-analysis.yml, .github/workflows/release-main.yaml, .gitignore, .goreleaser.yml, README.md, make/go.mk, skopeo/skopeo.go, skopeo/static/skopeo-darwin-amd64, skopeo/static/skopeo-darwin-arm64, skopeo/static/skopeo-linux-amd64, skopeo/static/skopeo-linux-arm64, skopeo/static/skopeo-windows-amd64.exe, skopeo/static/skopeo-windows-arm64.exe
This increases build time, makes the project not go-gettable, but
saves storage and money in GitHub.
=> fix: Remove skopeo static builds from git-lfs

.gitignore, README.md, archive/archive_test.go, cmd/mindthegap/create/create.go, cmd/mindthegap/create/helmbundle/helm_bundle.go, cmd/mindthegap/create/imagebundle/image_bundle.go
Data is already stored as compressed so removing the gz suffix by default. This
is a breaking change but one that will only affect users that rely on the default
output file naming, which in reality should not be anyone.
=> fix!: Remove unnecessary gzip compression of bundles by default

cmd/mindthegap/importcmd/imagebundle/image_bundle.go, cmd/mindthegap/push/helmbundle/helm_bundle.go, cmd/mindthegap/push/imagebundle/image_bundle.go, cmd/mindthegap/serve/helmbundle/helm_bundle.go, cmd/mindthegap/serve/imagebundle/image_bundle.go, cmd/mindthegap/utils/glob.go, cmd/mindthegap/utils/glob_test.go
Handles file globs for `--image-bundle` and `--helm-bundle`.
This also will fail fast if the file does not exist.
```
➜  mindthegap git:(dkoshkin/globs) ✗ dist/mindthegap_darwin_amd64_v1/mindthegap push image-bundle --image-bundle="glob-test/*.tar" --image-bundle=glob-test-2/dkoshkin-images1.tar --to-registry=127.0.0.1:5000 --to-registry-insecure-skip-tls-verify=true
✓ Unarchiving image bundle "glob-test-2/dkoshkin-images1.tar"
✓ Parsing image bundle config
✓ Unarchiving image bundle "glob-test/dkoshkin-images1.tar"
✓ Parsing image bundle config
✓ Unarchiving image bundle "glob-test/dkoshkin-images2.tar"
✓ Parsing image bundle config
✓ Starting temporary Docker registry
✓ Copying docker.io/library/busybox:latest (from bundle) to …
```
=> feat: support globs for image and helm bundles

go.mod, go.sum, make/go.mk, test/e2e/helmbundle/create_bundle_test.go, test/e2e/helmbundle/helm_bundle_suite_test.go, test/e2e/helmbundle/helpers/helpers.go, test/e2e/helmbundle/push_bundle_test.go, test/e2e/helmbundle/serve_bundle_test.go, test/e2e/imagebundle/helpers/docker.go, test/e2e/imagebundle/helpers/helpers.go, test/e2e/imagebundle/imagebundle_suite_test.go, test/e2e/imagebundle/import_bundle_test.go, test/e2e/imagebundle/testdata/import-bundle.yaml
This test uses Docker to spin up a container based on a KinD image which contains containerd. `mindthegap` binary and a created image bundle are copied to the container, `import image-bundle` is run, and then the image ID is retrieved from containerd via `crictl`. A known image ID is used to ensure that it does not change and to prevent regressions.
Depends on #191.
=> test: Add e2e test for import image-bundle 

README.md, config/images_config.go, config/images_config_test.go, config/testdata/images/multiple_registries_with_multiple_images_with_multiple_tags_in_plain_text_file.txt, test/e2e/imagebundle/import_bundle_test.go, test/e2e/imagebundle/testdata/import-bundle.txt
Previously a user would have to specify a canonical image ref for images
even on Docker Hub. This fixes that by allowing user-friendly names that
users are likely more used to.
=> fix: Properly handle friendly image names

.envrc, .github/workflows/checks-macos.yml, .goreleaser.yml, .tool-versions, Dockerfile, make/docker.mk, make/skopeo.mk
This enables either using mindthegap without downloading the binary, or to build static registry images and serve inside the Kubernetes cluster.
=> feat: Add Docker image

docker/ecr/registry.go, docker/ecr/registry_test.go
Previously this was failing because `url.Parse` does not parse bare
hostnames into a valid URL. Using a regexp on the whole registry
address fixes this.
=> fix: Correctly identify ECR registries

skopeo-static/go.mod, skopeo-static/go.sum
Fixes CVE https://github.com/advisories/GHSA-m5m3-46gj-wch8.
=> fix: Upgrade github.com/sylabs/sif/v2@v2.8.1

cmd/mindthegap/create/imagebundle/image_bundle.go
Previously only the registry inspect output was emitted, but to
diagnose certain issues the connection to docker dameon should
also be included in error logs.
=> fix: Ensure docker daemon skopeo logging is output on error

containerd/ctr.go
This commit fixes a bug discovered when running containerd in an arm64 container (via qemu)
on Linux. Taking inspiration from
https://github.com/kubernetes-sigs/kind/blob/v0.17.0/pkg/build/nodeimage/imageimporter.go#L60
we now import all platforms and create digest images when importing.
Without this fix, importing would fail with `ctr: image might be filtered out` - this no longer happens.
=> fix: Import all platforms from image bundle

make/upx.mk
- build: Use lzma compression for better file size, and decrease upx level
- Revert "build: Remove broken upx test after compression (#300)"
=> build: Use lzma compression for better file size, and decrease upx level

cmd/mindthegap/create/imagebundle/image_bundle.go, cmd/mindthegap/importcmd/imagebundle/image_bundle.go, cmd/mindthegap/push/helmbundle/helm_bundle.go, cmd/mindthegap/push/imagebundle/image_bundle.go, go.mod, images/httputils/configurable_tls_transport.go, images/manifest.go, test/e2e/imagebundle/push_bundle_test.go, test/e2e/imagebundle/serve_bundle_test.go
This was supported by skopeo before migrating to crane so this PR reintroduces it
rather than leave a breaking change.
=> fix: Support docker certs.d host certs again

cmd/mindthegap/push/helmbundle/helm_bundle.go, cmd/mindthegap/push/imagebundle/image_bundle.go, docker/ecr/registry.go, docker/ecr/registry_test.go, docker/ecr/repository.go
current implementation will not allow uploading images to ECR in AWS region other than "us-west-2". 
This PR
- extracts region from private ECR registry URI and uses it to create AWS client
- modify ECR registry address to support all endpoints including `fips` https://docs.aws.amazon.com/general/latest/gr/ecr.html
- Unit tests
Steps to reproduce:
- export AWS_REGION=us-west-1
- eval $(maws li eng-ksphere-platform)
- create small image bundle using `dkp create image-bundle --images-file images.yaml`
- upload image bundle to `us-west-1` ECR registry
```shell
❯ dkp push image-bundle --image-bundle images.tar \
--to-registry 999867407951.dkr.ecr.us-west-1.amazonaws.com \
--to-registry-username AWS \
--to-registry-password $(aws ecr get-login-password)
✓ …
```
=> fix: remove hardcoded AWS region when creating ECR lifecycle policies

docker/ecr/repository.go
Made a stupid mistake on the second commit https://github.com/mesosphere/mindthegap/pull/386
=> fix: using wrong argument when building ECR repository

cmd/mindthegap/create/imagebundle/image_bundle.go, cmd/mindthegap/importcmd/imagebundle/image_bundle.go, cmd/mindthegap/push/bundle/bundle.go, images/httputils/configurable_tls_transport.go, images/httputils/insecure_tls_transport.go, test/e2e/imagebundle/push_image_bundle_test.go, test/e2e/imagebundle/serve_image_bundle_test.go
~No need to Clone delegateTransport on every function call, we can reuse the same http.Transport for every call.~
Close idle connections.
=> fix: Separate out source and destination remote options

.golangci.yml, cmd/mindthegap/root/root.go
The Docker registry that is embedded in mindthegap reads `REGISTRY_` prefixed
environment variables, which could lead to unexpected behaviour depending on
the environment. This commit unsets these environment variables to ensure
consistent behaviour independent of environment.
Fixes D2IQ-97438.
=> fix: Unset REGISTRY_ prefixed env vars

.github/workflows/checks.yml, cmd/mindthegap/create/helmbundle/helm_bundle.go, cmd/mindthegap/create/imagebundle/image_bundle.go, cmd/mindthegap/flags/custom_flags.go, cmd/mindthegap/flags/custom_flags_test.go, cmd/mindthegap/flags/utils.go, cmd/mindthegap/importcmd/imagebundle/image_bundle.go, cmd/mindthegap/push/bundle/bundle.go, cmd/mindthegap/serve/bundle/bundle.go, cmd/mindthegap/utils/extract_bundles.go, docker/ecr/repository.go, go.mod, go.sum, test/e2e/imagebundle/helpers/helpers.go, test/e2e/imagebundle/push_bundle_test.go, test/e2e/imagebundle/serve_bundle_test.go
This allows the user to skip or error on existing image tags when pushing.
=> feat: Add --on-existing-tag flag to push bundle

cmd/mindthegap/create/imagebundle/image_bundle.go, cmd/mindthegap/push/bundle/bundle.go
Warnings such as the following cause confusion for no reason - everything is working as expected:
```
2023/09/13 17:32:25 retrying without mount: POST
UNAUTHORIZED: project istio not found: project istio not found
```
=> fix: Hide crane warnings by default

.github/workflows/checks-macos.yml, .github/workflows/checks.yml, .github/workflows/codeql-analysis.yml, .github/workflows/devbox-update.yaml, .github/workflows/release-tag.yaml
GH org was renamed as part of company rebranding.
=> ci: Switch to jetify-com/devbox-install-action

go.mod
Nix (and therefore devbox) has been slow in rolling out go1.22.2, which
contains CVE fixes. Current version go1.22.1 causes govulncheck to
report valid vulnerabilities in `net/http` package. go1.21 introduced
toolchain management via `go.mod` file with `toolchain` directive. This
commit specifies go1.22.2 as the toolchain to use and hence fixes the
govulncheck issues.
This does mean that go versions have to be managed in multiple places so
this is a stop-gap until Nix releases go1.22.2 to nixpkgs-unstable
channel.
=> build: Specify go1.22.2 as toolchain to fix govulncheck issues

helm/client.go, test/e2e/helmbundle/push_bundle_test.go, test/e2e/helmbundle/serve_bundle_test.go, test/e2e/helmbundle/testdata/create-success.yaml
Currently `mindthegap create helm-bundle` fails if the chart published in
the helm repo has a different name to the expected format
`<chartName>-<chartVersion>.tgz`. An example that hit this issue is the NFD
chart that is published with the name
`<chartName>-chart-<chartVersion>.tgz`.
This commit fixes the issue by first finding the download URL from the
Helm repo index and then using the existing `GetChartFromURL` function
to download the chart. This already correctly uses the basename of the
published chart file and hence doesn't hit the above issue.
Tested to be working:
```bash
$ cat repos.yaml
repositories:
nfd:
repoURL: https://kubernetes-sigs.github.io/node-feature-discovery/charts/
charts:
node-feature-discovery:
- 0.15.2
$ ./dist/mindthegap_darwin_arm64/mindthegap create …
```
=> fix: Support published Helm charts with different name format

.gitlint
Now that workflows use SHA-pinned actions rather than tagged versions,
dependabot commits are long causing failures in gitlint. This commit
fixes that by ignoring the specific lines that cause this issue.
=> build: Ignore long lines for commit shas

test/e2e/imagebundle/push_bundle_test.go, test/e2e/imagebundle/serve_bundle_test.go
This allows running the e2e tests on arm64 dev machines.
=> test(e2e): Specify architecture for test images in e2e

cmd/mindthegap/create/bundle/bundle.go, cmd/mindthegap/create/create.go, cmd/mindthegap/create/helmbundle/helm_bundle.go, cmd/mindthegap/create/imagebundle/image_bundle.go, cmd/mindthegap/flags/platforms_flag.go, cmd/mindthegap/flags/platforms_flag_test.go, test/e2e/helmbundle/helpers/helpers.go, test/e2e/imagebundle/helpers/helpers.go
This handles both image and helm charts config files so can be used
to replace both of the individual subcommands, which are now deprecated.
=> feat: Add single create bundle command

.github/workflows/checks-macos.yml, .github/workflows/checks.yml
This was used for taskfile experiment which is now integrated
so this env var is no longer needed.
=> ci: Remove redundant env var

go.mod
This was highlighted by failing govulncheck builds in
other PRs.
Fixes https://pkg.go.dev/vuln/GO-2024-2963.
=> build: Use go 1.22.5 toolchain to fix CVE

README.md, cmd/mindthegap/push/bundle/bundle.go, images/manifest.go, test/e2e/imagebundle/helpers/helpers.go, test/e2e/imagebundle/push_bundle_test.go, test/e2e/imagebundle/serve_bundle_test.go
This enables support for stricter registries, such as zot, as well as enabling
users to move to a future without vendor specific Docker media types.
=> feat: Optionally force convert to OCI media types on push

cmd/mindthegap/create/bundle/bundle.go, helm/client.go, test/e2e/helmbundle/helpers/helpers.go, test/e2e/helmbundle/serve_bundle_test.go, test/e2e/imagebundle/serve_bundle_test.go
This fix allows us to test the `serve bundle` command using a TLS client.
Previously, we created our own registryClient. We were responsible for configuring TLS for the client, but did not. We now allow helm to create the client for us. Because we previously did not customize the client in any way, we only gain functionality, and lose none.
=> fix: Allow TLS to pull chart from OCI repository

cmd/mindthegap/serve/bundle/bundle.go, devbox.json, devbox.lock, test/e2e/imagebundle/serve_bundle_test.go
This allows for specifying different repositories for a previously
built bundle, very useful when building air-gapped environments to
mimic Harbor which requires inserting a prefix for the project name.
=> feat: Support repository path prefix for serve bundle

.github/dependabot.yml, go.mod, go.sum
=> build: Only update github.com/docker/* with go-containerregistry

devbox.lock, tasks/build.yaml, test/e2e/helmbundle/push_bundle_test.go, test/e2e/helmbundle/serve_bundle_test.go, test/e2e/imagebundle/import_bundle_test.go, test/e2e/imagebundle/push_bundle_test.go, test/e2e/imagebundle/serve_bundle_test.go
`image-bundle` and `helm-bundle` were deprecated a while back in favour of a single `bundle` subcommand so updating e2e to reflect this.
=> test(e2e): Remove use of deprecated subcommands

go.mod, go.sum
Fixes CVE https://pkg.go.dev/vuln/GO-2025-3540.
=> build: Bump github.com/redis/go-redis/v9@v9.7.3

cmd/copy-file-to-pod/go.mod, cmd/wait-for-file-to-exist/go.mod, go.mod
Fixes https://pkg.go.dev/vuln/GO-2025-3563.
=> feat: go 1.24.2 to fix CVE

cmd/mindthegap/create/bundle/bundle.go
export `PullImagesAndOCIArtifacts` func so that it can be consumed in the new catalog CLI
=> refactor: export PullImagesAndOCIArtifacts function

docker/registry/storage/driver/archive/driver.go, test/e2e/imagebundle/push_bundle_test.go, test/e2e/imagebundle/testdata/create-success-busybox.yaml
This PR includes 2 commits, the first adding an e2e test that fails before the fix from the second commit is applied.
Details of the fix:
Previously, this was using `os.IsNotExist` error checking, but since the
move to using `ArchiveFS` from `github.com/mholt/archives` this should
have been changed to `errors.Is(err, fs.ErrNotExist)` which is now the
standard way to check filesystem errors with `fs.FS` based filesystems.
=> fix: Correctly check not found errors in registry storage

cmd/mindthegap/push/bundle/bundle.go, test/e2e/imagebundle/push_bundle_test.go
This commit outputs the bundle push output better for non-interactive TTY outputs rather than always using the gauge output.
Example output:
```
2025-09-09 10:44:07 INF  • Creating temporary directory...
2025-09-09 10:44:07 INF  • Extracting bundle configs from "large-bundle.tar"...
✓ Extracting bundle configs from "large-bundle.tar"
2025-09-09 10:44:07 INF  • Parsing image bundle config...
✓ Parsing image bundle config
2025-09-09 10:44:07 INF  • Starting temporary Docker registry...
✓ Starting temporary Docker registry
2025-09-09 10:44:08 INF  • [1/112] Pushing docker.io/nutanix/ntnx-csi:3.3.4...
2025-09-09 10:44:08 INF  ✓ [1/112] Pushing docker.io/nutanix/ntnx-csi:3.3.4
2025-09-09 10:44:08 INF  • [2/112] Pushing …
```
=> feat: Improved output for push bundle with non-interative TTY
